### ISSUE TITLE
Jndi log4j vulnerability in fabric-sdk-java v2.1.1?

### ISSUE THREAD

**Issue by subhasisbanik** [hyperledger/fabric-sdk-java#161]
I would like to know if using fabric-sdk-java v2.1.1 does contain the log4j vulnerability issue(https://www.wired.com/story/log4j-flaw-hacking-internet/) since they have the below dependencies in the main pom.xml:

-<dependency>

<groupId>log4j</groupId>

<artifactId>log4j</artifactId>

<version>${log4j.version}</version>

</dependency>

-<dependency>

<groupId>log4j</groupId>

<artifactId>apache-log4j-extras</artifactId>

<version>${log4j.version}</version>

</dependency>

Please help clarify this.

**Comment by denyeart** [comment]
Update merged in https://github.com/hyperledger/fabric-sdk-java/pull/158 , will be released soon.
