### ISSUE TITLE
NetworkConfig.getPrivateKeyFromString read private key exception

### ISSUE THREAD

**Issue by lunevvs** [hyperledger/fabric-sdk-java#175]
Hello

When the private key is in a non-standard (in my case ECDSA), org.bouncycastle.openssl.PEMParser.readObject() returns an instance of the PEMKeyPair class (it's written in the documentation) and then the org.hyperledger.fabric.sdk.NetworkConfig.getPrivateKeyFromString crashes with an exception:
```java-log
Caused by: java.lang.ClassCastException: class org.bouncycastle.openssl.PEMKeyPair cannot be cast to class org.bouncycastle.asn1.pkcs.PrivateKeyInfo (org.bouncycastle.openssl.PEMKeyPair and org.bouncycastle.asn1.pkcs.PrivateKeyInfo are in unnamed module of loader 'app')
```

Screenshot:
 ![image_2021-12-18_23-47-25](https://user-images.githubusercontent.com/23407409/146655914-f28e9e6f-f87d-4bd6-8579-a5db6b25e955.png)

Private key like this (values replace to '***'):
![image](https://user-images.githubusercontent.com/23407409/146656116-9fc6ff0a-9faf-4eae-8438-a7975c6dbdb0.png)

I`m use fabric-sdk-java:1.4.x, but this problem not fixed in last sources:
https://github.com/hyperledger/fabric-sdk-java/blob/v2.2.10/src/main/java/org/hyperledger/fabric/sdk/NetworkConfig.java#L945

**Comment by bestbeforetoday** [comment]
The current code is expecting a PKCS8 format private key. It could be changed to be less sensitive to the format with code similar to this:

https://github.com/hyperledger/fabric-gateway-java/blob/26c69ebc3ca5f23d0a8ee5efa9ffbd962a78f54b/src/main/java/org/hyperledger/fabric/gateway/Identities.java#L144-L154

As a workaround, I suggest converting the key data within your connection profile to PKCS8 format.

**Comment by bestbeforetoday** [comment]
The SDK uses standard PKCS#8 format private key PEM. I don't think it is worth increasing complexity to add support for the legacy EC format private key PEM.
