### ISSUE TITLE
Customization in the number of connections to hlf peer is unavailable and uses large number of threads

### ISSUE THREAD

**Issue by subhasisbanik** [hyperledger/fabric-sdk-java#176]
This sdk inherently sets up large number of threads which I believe is done from a connection pool to the hlf peer. I did not find any documentation to set the same. 
Please help me provide the configuration and the steps to implement the same.

**Comment by bestbeforetoday** [comment]
There is a `org.hyperledger.fabric.sdk.client.thread_executor_maximumpoolsize` configuration property that defaults to `Integer.MAX_VALUE`, so effectively unlimited.

**Comment by bestbeforetoday** [comment]
Closing as this has been stale for a while, so assuming the issue is resolved by configuration options above.
