### ISSUE TITLE
log4j update dependency

### ISSUE THREAD

**Issue by lesleyannjordan** [hyperledger/fabric-sdk-java#177]
Priority - please update to use log42.17.0

https://logging.apache.org/log4j/2.x/security.html

**Comment by jkneubuh** [comment]
main branch looks good with Mark's latest updates, but there's still a build error on release-2.2, e.g. : 

https://dev.azure.com/Hyperledger/Fabric-SDK-Java/_build/results?buildId=45678&view=results

**Comment by denyeart** [comment]
I've just merged the PRs for release-2.2 and release-1.4. Mark can kick off the Java SDK releases when he returns.
