### ISSUE TITLE
release-2.2 mutual tls config key and peer property key not matching

### ISSUE THREAD

**Issue by irririki** [hyperledger/fabric-sdk-java#260]
Here is the extraction from my connection profile:

```
 "peers":{
    "peer0": {
      "tlsCACerts": {
        "path": "./tls/tlscacerts/tlsca.pem",
        "client": {
          "certfile": "./tls/signcerts/sign.pem",
          "keyfile": "./tls/keystore/key.pem"
        }
      }, 
      "url": "grpcs://xx.xx.xx.xx:7051"
    }
  },
```

and here is the code:
```
Path walletDirectory = Paths.get("wallet");
Wallet wallet = Wallets.newFileSystemWallet(walletDirectory);

// Path to a common connection profile describing the network.
Path networkConfigFile = Paths.get("connection_profile.json");

// Configure the gateway connection used to access the network.
Gateway.Builder builder = Gateway.createBuilder()
        .identity(wallet, "admin")
        .networkConfig(networkConfigFile);

// Create a gateway connection
try (Gateway gateway = builder.connect()) {
 

    // Obtain a smart contract deployed on the network.
    Network network = gateway.getNetwork("dev");
    
    Contract contract = network.getContract("fabcar");

} catch (ContractException e) {
    e.printStackTrace();
}
```

The problem happens at 2 places. The first one is:
```
 .networkConfig(networkConfigFile);
```
where in NetworkConfig.java, it will put in props the key 'tlsClientKeyFile'. 
```
if (keyfile != null) {
    props.put("tlsClientKeyFile", keyfile);
}

if (certfile != null) {
    props.put("tlsClientCertFile", certfile);
}
```
See https://github.com/hyperledger/fabric-sdk-java/blob/3dfc858bb7d6e19d9f7730874841bf663951cb5a/src/main/java/org/hyperledger/fabric/sdk/NetworkConfig.java#L845-L862

This change was introduced since v2.2.4.

Then it goes on to the line:
```
Network network = gateway.getNetwork("dev");
```
where, in Endpoint.java, it tries to find 'clientKeyFile' in the properties
```
if (properties.containsKey("clientKeyFile") || properties.containsKey("clientCertFile")) {
```
See https://github.com/hyperledger/fabric-sdk-java/blob/3dfc858bb7d6e19d9f7730874841bf663951cb5a/src/main/java/org/hyperledger/fabric/sdk/Endpoint.java#L175-L198

Since the property has a different name, the method return null, which results on the peer side returning an error saying the client didn't send the certificate.

**Comment by irririki** [comment]
By changing the code in NetworkConfig.java to mache the certFile and keyFile key names, it works. I have tested with my local fix.

`if (keyfile != null) {
                    props.put("clientKeyFile", keyfile);
                }

                if (certfile != null) {
                    props.put("clientCertFile", certfile);
                }`

**Comment by bestbeforetoday** [comment]
This looks like something that has never worked, and perhaps wasn't intended to. The change you refer to just introduced some new functionality and didn't change any existing property naming set by NetworkConfig. It seems by happy coincidence that it would provide the capability you are looking for too though.

The Endpoint code is picking up properties set either explicitly if nodes are programmatically added, or from configuration and/or environment variables when nodes are added by service discovery, here:

- Peer: https://github.com/hyperledger/fabric-sdk-java/blob/4d3cfc581c963ecc790bb429c6fe4a78e3312294/src/main/java/org/hyperledger/fabric/sdk/Channel.java#L1696-L1713
- Orderer: https://github.com/hyperledger/fabric-sdk-java/blob/4d3cfc581c963ecc790bb429c6fe4a78e3312294/src/main/java/org/hyperledger/fabric/sdk/Channel.java#L1630-L1649

Your suggested enhancement seems reasonable, although I think "tlsClientKeyFile", "tlsClientCertFile", "tlsClientKeyBytes" and "tlsClientCertBytes" would all need to change to the forms without the leading "tls" to match the Endpoint code. Note that these properties are also used in HFClient, here:

https://github.com/hyperledger/fabric-sdk-java/blob/4d3cfc581c963ecc790bb429c6fe4a78e3312294/src/main/java/org/hyperledger/fabric_ca/sdk/HFCAClient.java#L1620-L1630

I think the changes required would be:

- [ ] Change "tlsClient..." properties set in NetworkConfig to "client...".
- [ ] Change the corresponding property names in HFCAClient.
- [ ] Some unit testing (at least in NetworkConfigTest).
- [ ] Extract the strings hard-coded in all these locations to internal constants, probably in Endpoint

Would you like to implement these changes?

**Comment by irririki** [comment]
Happy to do so.

**Comment by irririki** [comment]
@bestbeforetoday I have made the changes, but it seems that I can't create a new pull request. Could you have a look?
 
https://github.com/irririki/fabric-sdk-java-260

- [X] Change "tlsClient..." properties set in NetworkConfig to "client...".
- [X]  Change the corresponding property names in HFCAClient.
- [X]  Some unit testing (at least in NetworkConfigTest). -  NetworkConfigTest and HFCAClientTest.java
- [X]  Extract the strings hard-coded in all these locations to internal constants, probably in Endpoint - except HFCAClient

[WARNING] Tests run: 444, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.443 s
[INFO] Finished at: 2023-02-07T12:14:03+09:00
[INFO] ------------------------------------------------------------------------

**Comment by bestbeforetoday** [comment]
I think the problem might be that your repository is not a **fork** if this repository. The repository with your changes needs to be a fork of the repository to which you want to propose changes by creating a pull request. See the GitHub documentation on how to [fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo). Then the documentation on [creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
