### ISSUE TITLE
fanric-java-sdk how to use Taking ledger snapshots and using them to join channels

### ISSUE THREAD

**Issue by VastlyEternal** [hyperledger/fabric-sdk-java#276]
fanric-java-sdk how to use Taking ledger snapshots and using them to join channels

**Comment by VastlyEternal** [comment]
Does java sdk support joining channels through the latest snapshot? No method was found about snapshots

**Comment by bestbeforetoday** [comment]
Joining channels using snapshots uses the peer CLI commands, as described in the Fabric [documentation](https://hyperledger-fabric.readthedocs.io/en/latest/peer_ledger_snapshot.html). The SDK does not support joining channels using snapshots.
